---
apiVersion: v1
kind: Namespace
metadata:
  name: bggns

---
apiVersion: v1 
kind: Service 
metadata: 
  name: bggdb-hsvc 
  namespace: bggns 
  labels:
    app: bgg
    name: bggdb-hsvc
spec:
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306

--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bggdb-sts
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-sts
spec:
  replicas: 1
  serviceName: bggdb-hsvc
  selector:
    matchLabels:
      app: bgg
      name: bggdb-po
  volumeClaimTemplates:
  - apiVersion: v1 
    kind: PersistentVolumeClaim 
    metadata:
      name: data-vol
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: do-block-storage
      resources: 
        requests: 
          storage: 1Gi
  template:
    metadata:
      name: bggdb-po
      labels:
        app: bgg
        name: bggdb-po
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: bggdb-port
          containerPort: 3306
        volumeMounts:
        - name: data-vol 
          mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: bggdb-port
