apiVersion: v1
kind: Namespace
metadata:
  labels:
    dept: eng
    env: test
  name: test-ns
---
apiVersion: v1
data:
  INSTANCE_NAME: this is from kustomize configmap generator
kind: ConfigMap
metadata:
  labels:
    dept: eng
    env: test
  name: test-dov-cm-2c7t77fkdf
  namespace: test-ns
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dov
    dept: eng
    env: test
    name: dov-svc
  name: test-dov-svc
  namespace: test-ns
spec:
  ports:
  - name: svc-web-port
    port: 5000
    targetPort: web-port
  - name: svc-metrics-port
    port: 5100
    targetPort: metrics-port
  selector:
    app: dov
    dept: eng
    env: test
    name: dov-po
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dov
    dept: eng
    env: test
    name: dov-deploy
  name: test-dov-deploy
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dov
      dept: eng
      env: test
      name: dov-po
  template:
    metadata:
      labels:
        app: dov
        dept: eng
        env: test
        name: dov-po
      name: dov-po
    spec:
      volumes:
      - emptyDir: {}
        name: my-vol
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    dept: eng
    env: test
  name: test-dov-hpa
  namespace: test-ns
spec:
  maxReplicas: 4
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-dov-deploy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: dov
    dept: eng
    env: test
    name: dov-ing
  name: test-dov-ing
  namespace: test-ns
spec:
  ingressClassName: nginx
  rules:
  - host: kustomize-139.59.223.166.nip.io
    http:
      paths:
      - backend:
          service:
            name: test-dov-svc
            port:
              name: svc-web-port
        path: /
        pathType: Prefix
