---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: codeserver-pvc 
  namespace: codeserver
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: do-block-storage 
  resources:
    requests:
      storage: 1Gi

--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: codeserver-deploy 
  namespace: codeserver 
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: codeserver
      name: codeserver-po
  template:
    metadata:
      name: codeserver-po
      labels:
        app: codeserver
        name: codeserver-po
    spec: 
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: codeserver-pvc
      containers:
      - name: codeserver-container
        image: linuxserver/code-server:4.22.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: codeserver-cm
        - secretRef: 
            name: codeserver-secret
        ports:
        - name: cs-port 
          containerPort: 8443
        volumeMounts:
        - name: data-vol 
          mountPath: /config/workspace

--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: codeserver-svc 
  namespace: codeserver 
spec:
  type: ClusterIP 
  selector: 
    app: codeserver
    name: codeserver-po
  ports: 
  - name: svc-cs-port 
    port: 8443 
    targetPort: cs-port

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata: 
  name: codeserver-ing 
  namespace: codeserver 
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/limit-rps: "10"

spec:
  ingressClassName: nginx 
  rules:
  - host: cs-139.59.223.166.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service: 
            name: codeserver-svc 
            port:
              name: svc-cs-port