---
apiVersion: v1
kind: Namespace
metadata:
  name: codeserver

---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: codeserver-cm
  namespace: codeserver
  labels:
    app: codeserver
    name: codeserver-cm
data:
  TZ: Asia/Singapore
  PROXY_DOMAIN: cs-139.59.223.166.nip.io
  DEFAULT_WORKSPACE: /config/workspace

---
apiVersion: v1 
kind: Secret 
metadata:
  name: codeserver-secret
  namespace: codeserver
  labels:
    app: codeserver
    name: codeserver-secret
type: Opaque
data:
  # hellohello
  PASSWORD: aGVsbG9oZWxsbw==
  # hellohello
  SUDO_PASSWORD: aGVsbG9oZWxsbw==