---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm 
  namespace: minio-ns
data:
  # adminadmin
  MINIO_CI_CD: "1"

--- 
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret 
  namespace: minio-ns
type: Opaque
data:
  # adminadmin
  MINIO_ROOT_USER: YWRtaW5hZG1pbg==
  MINIO_ROOT_PASSWORD: YWRtaW5hZG1pbg==
