---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio-ns
  labels:
    app: minio
    name: minio-hsvc
spec:
  clusterIP: None
  selector:
    app: minio 
    name: minio-po
  ports:
  - name: data-port
    port: 9000
    targetPort: 9000
  - name: web-port
    port: 9090
    targetPort: 9090

---
apiVersion: apps/v1 
kind: StatefulSet 
metadata:
  name: minio-sts
  namespace: minio-ns
  labels:
    app: minio
    name: minio-sts
spec:
  replicas: 3
  serviceName: minio-hsvc
  selector:
    matchLabels:
      app: minio 
      name: minio-po
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data-vol
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: do-block-storage 
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      name: minio-po
      labels:
        app: minio 
        name: minio-po
    spec:
      initContainers:
      - name: minio-init
        image: busybox
        imagePullPolicy: IfNotPresent
        command: 
        - /bin/sh 
        - -c 
        - "chown 1001:1001 /opt/data"
        volumeMounts:
        - name: data-vol
          mountPath: /opt/data
      containers:
      - name: minio-container
        image: bitnami/minio:2023.12.23
        imagePullPolicy: IfNotPresent
        command: #exec
        - minio
        - server
        - --address=:9000
        - --console-address=:9090
        - minio-sts-{0...2}.minio-hsvc.minio.svc.cluster.local/opt/data 
        envFrom:
        - configMapRef:
            name: minio-cm
        - secretRef:
            name: minio-secret
        ports:
        - name: data-port
          containerPort: 9000
        - name: web-port
          containerPort: 9090
        volumeMounts:
        - name: data-vol
          mountPath: /opt/data

---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio-ns
  labels:
    app: minio
    name: minio-svc
spec:
  type: ClusterIP
  selector:
    app: minio 
    name: minio-po
  ports:
  - name: data-port
    port: 9000
    targetPort: 9000
  - name: web-port
    port: 9090
    targetPort: 9090

---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: minio-ing 
  namespace: minio-ns
  labels:
    app: minio
    name: minio-ing 
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  ingressClassName: nginx
  rules:
  - host: console-139.59.223.166.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              name: web-port
  - host: data-139.59.223.166.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              name: data-port


